"use client";
import { useCallback, useEffect, useState } from "react";
import { authFetch } from "@/lib/auth-fetch";
type Request = { id: string; name: string; email: string; createdAt: string };
type Workspace = { id: string; name: string };
export function AccessApprovalPopup() {
  const [requests, setRequests] = useState<Request[]>([]); const [workspaces, setWorkspaces] = useState<Workspace[]>([]); const [workspaceId, setWorkspaceId] = useState(""); const [role, setRole] = useState("member"); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { const response = await authFetch("/api/access-requests"); if (!response.ok) return; const result = await response.json() as { requests: Request[]; workspaces: Workspace[] }; setRequests(result.requests); setWorkspaces(result.workspaces); setWorkspaceId((current) => current || result.workspaces[0]?.id || ""); }, []);
  useEffect(() => { const first = window.setTimeout(() => void load(), 0); const timer = window.setInterval(() => void load(), 10000); return () => { window.clearTimeout(first); window.clearInterval(timer); }; }, [load]);
  const current = requests[0]; if (!current) return null;
  async function approve() { if (!workspaceId) { setError("Create or choose a workspace first."); return; } setSaving(true); setError(""); try { const response = await authFetch("/api/access-requests", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ requestId: current.id, workspaceId, role }) }); const result = await response.json() as { error?: string }; if (!response.ok) { setError(result.error || "Could not approve this user."); return; } setRequests((items) => items.slice(1)); } catch { setError("Unable to connect to TeamFlow."); } finally { setSaving(false); } }
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/75 p-5 backdrop-blur-sm"><section role="dialog" aria-modal="true" aria-labelledby="approval-title" className="w-full max-w-lg rounded-3xl border border-violet-400/30 bg-slate-900 p-7 shadow-2xl"><p className="text-sm font-semibold text-violet-300">NEW USER REQUEST</p><h2 id="approval-title" className="mt-2 text-2xl font-bold">Choose workspace access</h2><div className="mt-5 rounded-2xl bg-slate-950/70 p-4"><p className="font-semibold">{current.name}</p><p className="mt-1 text-sm text-slate-400">{current.email}</p><p className="mt-2 text-xs text-emerald-300">Email verified · waiting for your decision</p></div><label className="mt-5 block text-sm font-medium">Workspace<select value={workspaceId} onChange={(event) => setWorkspaceId(event.target.value)} className="mt-2 w-full rounded-xl border border-white/15 bg-slate-950 px-4 py-3"><option value="">Choose workspace</option>{workspaces.map((space) => <option key={space.id} value={space.id}>{space.name}</option>)}</select></label><label className="mt-4 block text-sm font-medium">Access role<select value={role} onChange={(event) => setRole(event.target.value)} className="mt-2 w-full rounded-xl border border-white/15 bg-slate-950 px-4 py-3"><option value="member">Member — no payment</option><option value="admin">Admin — no payment</option></select></label><p className="mt-3 text-xs leading-5 text-slate-400">Invited Members and Admins enter immediately. Only the TeamFlow platform Owner pays at login.</p>{error && <p className="mt-3 text-sm text-red-300">{error}</p>}<button type="button" onClick={() => void approve()} disabled={saving} className="mt-6 w-full rounded-xl bg-violet-500 px-5 py-3 font-semibold hover:bg-violet-400 disabled:opacity-60">{saving ? "Saving…" : `Grant ${role} access`}</button>{requests.length > 1 && <p className="mt-3 text-center text-xs text-slate-500">{requests.length - 1} more request(s) waiting</p>}</section></div>;
}
