"use client";
import { useState } from "react";
import Image from "next/image";
import { authFetch } from "@/lib/auth-fetch";
type Profile = { name: string; phone: string | null; jobTitle: string | null; bio: string | null; avatarDataUrl: string | null };
export function ProfileForm({ profile }: { profile: Profile }) {
  const [form, setForm] = useState({ name: profile.name, phone: profile.phone || "", jobTitle: profile.jobTitle || "", bio: profile.bio || "", avatarDataUrl: profile.avatarDataUrl || "" });
  const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function save(event: React.FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); try { const response = await authFetch("/api/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const result = await response.json() as { error?: string }; setMessage(response.ok ? "Profile saved." : result.error || "Could not save your profile."); } catch { setMessage("Unable to connect to TeamFlow."); } finally { setSaving(false); } }
  function chooseAvatar(file: File | null) { if (!file) return; if (!/^image\/(png|jpeg|webp)$/.test(file.type) || file.size > 1_000_000) { setMessage("Choose a PNG, JPEG, or WebP image smaller than 1 MB."); return; } const reader = new FileReader(); reader.onload = () => setForm((current) => ({ ...current, avatarDataUrl: typeof reader.result === "string" ? reader.result : "" })); reader.readAsDataURL(file); }
  const input = "mt-1 w-full rounded-xl border border-white/15 bg-slate-950 px-4 py-3 outline-none focus:border-violet-400";
  return <form onSubmit={save} className="rounded-3xl border border-white/10 bg-white/[0.04] p-6 sm:p-7"><div><h2 className="text-xl font-semibold">Personal information</h2><p className="mt-1 text-sm text-slate-400">Keep your details current so teammates know who they are working with.</p></div><div className="mt-6 flex flex-wrap items-center gap-4"><div className="flex h-20 w-20 items-center justify-center overflow-hidden rounded-2xl border border-white/15 bg-violet-500/20 text-2xl font-bold">{form.avatarDataUrl ? <Image src={form.avatarDataUrl} alt="Profile preview" width={80} height={80} unoptimized className="h-full w-full object-cover" /> : form.name[0]?.toUpperCase()}</div><div className="flex flex-wrap gap-2"><label className="cursor-pointer rounded-xl border border-white/15 px-4 py-2 text-sm font-medium transition hover:bg-white/10">Upload photo<input type="file" accept="image/png,image/jpeg,image/webp" className="sr-only" onChange={(event) => chooseAvatar(event.target.files?.[0] ?? null)} /></label>{form.avatarDataUrl && <button type="button" onClick={() => setForm({ ...form, avatarDataUrl: "" })} className="rounded-xl px-4 py-2 text-sm text-slate-400 hover:bg-white/5 hover:text-white">Remove</button>}<p className="w-full text-xs text-slate-500">PNG, JPEG, or WebP. Maximum 1 MB.</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Full name<input required maxLength={80} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className={input} /></label><label className="text-sm font-medium">Job title<input maxLength={100} value={form.jobTitle} onChange={(event) => setForm({ ...form, jobTitle: event.target.value })} className={input} placeholder="Product designer" /></label><label className="text-sm font-medium sm:col-span-2">Phone number<input maxLength={30} value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} className={input} placeholder="+91 98765 43210" /></label></div><label className="mt-4 block text-sm font-medium">About you<textarea value={form.bio} onChange={(event) => setForm({ ...form, bio: event.target.value })} maxLength={500} rows={5} className={`${input} resize-y`} placeholder="Share your role, skills, and what you are working on." /><span className="mt-1 block text-right text-xs text-slate-500">{form.bio.length}/500</span></label><div className="mt-5 flex flex-wrap items-center gap-4"><button disabled={saving} className="rounded-xl bg-violet-500 px-5 py-3 font-semibold transition hover:bg-violet-400 disabled:opacity-60">{saving ? "Saving…" : "Save changes"}</button>{message && <p role="status" className="text-sm text-slate-300">{message}</p>}</div></form>;
}
